//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public int ReleaseID { get; set; }
        public string ReleaseTitle { get; set; }
        public string Region { get; set; }
        public int ProjectID { get; set; }
        public bool ProdPreview { get; set; }
        public System.DateTime ProdPreviewDate { get; set; }
        public bool ProdCD { get; set; }
        public System.DateTime ProdCDDate { get; set; }
        public string DeploymentType { get; set; }
        public bool ContainSourceFile { get; set; }
        public bool RequireBuild { get; set; }
        public bool ContainSitecorePackage { get; set; }
        public bool ContainThirdPartyService { get; set; }
        public int DefaultLanguageID { get; set; }
        public bool IsMultilingual { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string Reviewer { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
