//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePlace.Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseService
    {
        public int ReleaseID { get; set; }
        public int ServiceID { get; set; }
    }
}
